project:
  type: website

website:
  title: "David Hall"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - posts.qmd

# Enable publishing to GitHub Pages
publish:
  provider: gh-pages
